name: rebase

on:
  workflow_dispatch: {}
  schedule:
  - cron: 0 0 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump firecracker
      run: |
        new_version=$(./hack/scripts/bump_firecracker.sh)
        if [[ "$new_version" == "" ]]; then
          echo "No new Firecracker release. Nothing to do. (this is not an error, no worries.)"
          exit 1
        fi

        echo 'NEW_VERSION<<EOF' >> $GITHUB_ENV
        echo "${new_version}" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Create PR
      if: ${{ success() }}
      uses: peter-evans/create-pull-request@v3
      id: cpr
      with:
        token: ${{ secrets.WEAVEWORKSBOT_TOKEN }}
        commit-message: Bump firecracker version in e2e tests to ${{ env.NEW_VERSION }}
        committer: weaveworksbot <weaveworksbot@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: bump-firecracker-${{ github.sha }}
        base: main
        delete-branch: true
        title: 'WIP feat[test]: bump firecracker version to ${{ env.NEW_VERSION }}'
        body: |
          This is an automatically generated PR to bump the version of firecracker
          in our tests. There are some manual steps to get new releases of our fork
          branch published.
          This PR is to track those manual steps.

          To complete work on this PR:
          - [ ] Update (merge or rebase) https://github.com/weaveworks/firecracker/tree/feature/macvtap
            to the latest upstream release tag ${{ env.NEW_VERSION }}.
          - [ ] Make sure it builds.
          - [ ] Push the updated firecracker 'feature/macvtap' fork branch.
            (A new [draft release](https://github.com/weaveworks/firecracker/releases) will be created.)
          - [ ] In this repo, trigger the `nightly_e2e` workflow to run on the
            `bump-firecracker-${{ github.sha }}` branch.
          - Once the tests have passed:
              - [ ] publish the release in our firecracker fork
              - [ ] edit the title of this PR to remove the 'WIP'
              - [ ] mark the PR as ready to review
              - [ ] approve and merge

          Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: |
          'area/testing'
          'area/firecracker'
          'area/dependency'
          'kind/feature'
        draft: true
  notify:
    needs: [build]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack on failure
      uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        message: "Updating the firecracker version failed :sad-parrot: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here>."
        channel: team-quick-silver
        color: red
        verbose: false
