name: releasenote

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Release notes check
    steps:
      - name: Check for release note
        id: rn
        uses: richardcase/release-note-action@v0.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}